org: clairechoi
app: deploy-chatbot
service: deploy-chatbot

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8

package:
  individually: false
  exclude:
    - package.json
    - package-log.json
    - node_modules/**

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /
          method: post

plugins:
  - serverless-python-requirements
