name: deploy-aws-lambda
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     node-version: [16.x]
    steps:
      - name: Checkout to repo
        uses: actions/checkout@v2

      - name: Setup node environment
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
          
      - name: Install serverless globally
        run: npm install -g serverless
      
      - name: Configure serverless authentication
        run: sls config credentials --provider aws --key ${{ secrets.AWS_ACCESS_KEY_ID }} --secret ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Install npm dependencies
        run: npm ci
     
      - name: Deploy lambda function
        run: sls deploy
    # steps:
    #   - uses: actions/checkout@v2
    #   - name: Use Node.js ${{ matrix.node-version }}
    #     uses: actions/setup-node@v1
    #     with:
    #       node-version: ${{ matrix.node-version }}
    #   - name: Install Dependencies
    #     run: npm install
    #   # - name: Configure AWS Credentials
    #   #   uses: aws-actions/configure-aws-credentials@v1
    #   #   with:
    #   #     # aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #   #     # aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #         # SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
    #   # - name: Serverless Deploy
    #   #   run: npm run-script deploy
    #   - name: serverless deploy
    #     uses: serverless/github-action@v3
    #     with:
    #       args: deploy
    #     env:
    #       aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #       aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}